package(default_visibility = ["//visibility:public"])

cc_test(
    name = "config_decode_test",
    size = "small",
    srcs = ["config_decode_test.cc"],
    deps = [
        "//src/primihub/common/config:config_lib",
        "@com_google_googletest//:gtest_main",
        "@com_github_jbeder_yaml_cpp//:yaml-cpp",
    ],
)
