version: '3'
services:
  mysql:
    image: $MYSQL_IMAGE
    container_name: mysql
    restart: always
    env_file:
      - ./data/env/mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: $REDIS_IMAGE
    container_name: redis
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
  
  nacos:
    image: $NACOS_IMAGE
    container_name: nacos-server
    restart: on-failure
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
      #- ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8848:8848"
      # - "9848:9848"
      # - "9555:9555"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8848/nacos"]
      interval: 10s
      timeout: 10s
      retries: 3

  rabbitmq0:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq0
    restart: always

  rabbitmq1:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq1
    restart: always

  rabbitmq2:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq2
    restart: always

  meta0:
    image: $PRIMIHUB_META
    container_name: primihub-meta0
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/meta.jar \
        --server.port=8080 \
        --grpc.server.port=9099 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo0 \
        --spring.cloud.nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.config.namespace=demo0"
    # ports:
    #   - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8080/fusion/healthConnection"]
      interval: 15s
      timeout: 3s
      retries: 3

  meta1:
    image: $PRIMIHUB_META
    container_name: primihub-meta1
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/meta.jar \
        --server.port=8080 \
        --grpc.server.port=9099 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo1 \
        --spring.cloud.nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.config.namespace=demo1"
    # ports:
    #   - "8081:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8080/fusion/healthConnection"]
      interval: 15s
      timeout: 3s
      retries: 3

  meta2:
    image: $PRIMIHUB_META
    container_name: primihub-meta2
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/meta.jar \
        --server.port=8080 \
        --grpc.server.port=9099 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo2 \
        --spring.cloud.nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.config.namespace=demo2"
    # ports:
    #   - "8082:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8080/fusion/healthConnection"]
      interval: 15s
      timeout: 3s
      retries: 3
  
  application0:
    image: $PRIMIHUB_PLATFORM
    container_name: application0
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar \
        --spring.rabbitmq.host=rabbitmq0 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo0 \
        --nacos.config.namespace=demo0"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8090/healthConnection"]
      interval: 10s
      timeout: 10s
      retries: 3

  application1:
    image: $PRIMIHUB_PLATFORM
    container_name: application1
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar \
        --spring.rabbitmq.host=rabbitmq1 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo1 \
        --nacos.config.namespace=demo1"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - application0

  application2:
    image: $PRIMIHUB_PLATFORM
    container_name: application2
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar \
        --spring.rabbitmq.host=rabbitmq2 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo2 \
        --nacos.config.namespace=demo2"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - application0

  gateway0:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway0
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar \
        --server.port=8080 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo0 \
        --nacos.config.namespace=demo0"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - application0

  gateway1:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway1
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar \
        --server.port=8080 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo1 \
        --nacos.config.namespace=demo1"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - application1
  
  gateway2:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway2
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar \
        --server.port=8080 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=demo2 \
        --nacos.config.namespace=demo2"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - application2

  nginx0:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: manage-web0
    restart: always
    volumes:
      - "./config/default0.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30811:80"
    depends_on:
      - gateway0

  nginx1:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: manage-web1
    restart: always
    volumes:
      - "./config/default1.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30812:80"
    depends_on:
      - gateway1

  nginx2:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: manage-web2
    restart: always
    volumes:
      - "./config/default2.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30813:80"
    depends_on:
      - gateway2

  node0:
    # shm_size: '6gb'  # ray's request,more than RAM 30% 
    image: $PRIMIHUB_NODE
    container_name: primihub-node0
    restart: "always"
    ports:
      - "50050:50050"
    volumes:
      # - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "GLOG_logtostderr=1 GLOG_v=2 ./primihub-node --config=/app/config/primihub_node0.yaml"
    # GLOG_v 0->7,the larger the value the more detailed the log
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      meta0:
        condition: service_healthy

  node1:
    # shm_size: '6gb'
    image: $PRIMIHUB_NODE
    container_name: primihub-node1
    restart: "always"
    ports:
      - "50051:50051"
    volumes:
      # - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "GLOG_logtostderr=1 GLOG_v=2 ./primihub-node --config=/app/config/primihub_node1.yaml"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      meta1:
        condition: service_healthy

  node2:
    # shm_size: '6gb'
    image: $PRIMIHUB_NODE
    container_name: primihub-node2
    restart: "always"
    ports:
      - "50052:50052"
    volumes:
      # - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "GLOG_logtostderr=1 GLOG_v=2 ./primihub-node --config=/app/config/primihub_node2.yaml"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      meta2:
        condition: service_healthy

  loki:
    image: $LOKI_IMAGE
    container_name: loki
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    volumes:
      - ./data:/data
    ports:
      - 3100:3100

networks:
  primihub_net: