/*
 * Copyright (c) 2026 by PrimiHub
 * Licensed under the Apache License, Version 2.0
 *
 * frodo_prng — seeded pseudorandom number generator interface for
 * the FrodoPIR C++ port. Wraps a deterministic stream cipher keyed
 * by a 32-byte seed. Used by GenerateLweMatrixFromSeed (chunk 2b-i,
 * see frodo_matrices.h) to expand a public seed into the LWE
 * matrix A; the same seed on both client and server must produce
 * the same A.
 *
 * Position in the port plan (docs/pir/frodo-port-plan.md):
 *   chunk 2b-i  — landed the SeededRng abstraction + LWE matrix
 *                 generation. Backed by std::mt19937_64 placeholder.
 *   chunk 2b-ii — THIS chunk; swapped the underlying engine to
 *                 OpenSSL ChaCha20 keeping the API surface fully
 *                 backwards-compatible. Restores cryptographic
 *                 security so the LWE matrix A satisfies the CSPRNG
 *                 requirement of the FrodoPIR security analysis.
 *   chunk 2b-iii — pending; native ChaCha12 port for upstream
 *                  rand_chacha::ChaCha12Rng byte-for-byte interop
 *                  (only matters if a deployment ever mixes our
 *                  C++ client with the Rust client).
 *
 * Cryptographic properties (post chunk 2b-ii):
 *   * IND-CPA secure under the standard ChaCha20 assumption — meets
 *     the FrodoPIR LWE-security argument's CSPRNG requirement.
 *   * Deterministic for a given 32-byte seed — same seed on client
 *     and server yields the same byte stream, so both sides derive
 *     the same LWE matrix A.
 *   * 32-byte seed is fed as the ChaCha20 key; the IV (16 bytes) is
 *     fixed all-zero. The combination "user-controlled key + fixed
 *     IV" is fine because the seed itself is the trust anchor: the
 *     FrodoPIR protocol publishes the seed and treats the resulting
 *     A as public. Two different seeds yield two cryptographically
 *     unrelated streams.
 *   * NOT byte-for-byte compatible with upstream rand_chacha::
 *     ChaCha12Rng's stream from the same seed — upstream uses
 *     ChaCha12 (12 rounds), we use ChaCha20 (20 rounds). Streams
 *     diverge from the very first block.
 *
 * Field-by-field correspondence with upstream Rust:
 *   fn get_seeded_rng(s: [u8; 32]) -> StdRng        ←→
 *       SeededRng(span<uint8_t, 32>) ctor
 *   StdRng::next_u32()                              ←→
 *       SeededRng::NextU32()
 *   StdRng::next_u64()                              ←→
 *       SeededRng::NextU64()
 *
 * Internal byte stream model: a 64-byte buffer holds one ChaCha20
 * block. NextU32 returns 4 little-endian bytes from the buffer,
 * advancing the read position; NextU64 returns 8. When the read
 * position reaches the end of the buffer, the next block is
 * generated by feeding 64 zero bytes through EVP_EncryptUpdate.
 * NextU32 followed by NextU64 (or vice versa) see a coherent
 * contiguous byte stream — boundaries between u32 and u64 reads
 * land at byte granularity, just as upstream rand_chacha's
 * BlockRngCore does.
 */
#ifndef SRC_PRIMIHUB_KERNEL_PIR_OPERATOR_FRODO_PIR_FRODO_PRNG_H_
#define SRC_PRIMIHUB_KERNEL_PIR_OPERATOR_FRODO_PIR_FRODO_PRNG_H_

#include <array>
#include <cstddef>
#include <cstdint>

// Forward-declare OpenSSL's opaque cipher context so callers don't
// need to include <openssl/evp.h>. The actual type comes from
// <openssl/types.h> via <openssl/evp.h> in frodo_prng.cc.
struct evp_cipher_ctx_st;

namespace primihub::pir::frodo {

// Seed type matching upstream `rand_core::SeedableRng::Seed = [u8; 32]`
// for rand_chacha::ChaCha12Rng. We keep std::array<uint8_t, 32> so the
// API stays unchanged across chunk 2b-i (mt19937 placeholder) and
// chunk 2b-ii (OpenSSL ChaCha20).
using SeedBytes = std::array<std::uint8_t, 32>;

class SeededRng {
 public:
  // Construct from a 32-byte seed. Two SeededRng instances built
  // from equal seeds produce equal infinite streams. Backed by
  // OpenSSL ChaCha20 since chunk 2b-ii — cryptographically secure
  // and suitable for FrodoPIR's CSPRNG requirement.
  explicit SeededRng(const SeedBytes& seed);

  // Resource cleanup of the OpenSSL EVP_CIPHER_CTX. Out-of-line so
  // the header doesn't need <openssl/evp.h>.
  ~SeededRng();

  // Non-copyable: EVP_CIPHER_CTX ownership is unique. Non-movable
  // for simplicity — every caller uses SeededRng as a stack value.
  SeededRng(const SeededRng&) = delete;
  SeededRng& operator=(const SeededRng&) = delete;
  SeededRng(SeededRng&&) = delete;
  SeededRng& operator=(SeededRng&&) = delete;

  // Returns the next 32-bit output of the stream as a little-endian
  // u32 of the next 4 bytes. Mirrors upstream `StdRng::next_u32()`
  // semantics (byte-stream-based). Consecutive calls advance the
  // read position by 4 bytes.
  std::uint32_t NextU32();

  // Returns the next 64-bit output of the stream as a little-endian
  // u64 of the next 8 bytes. Mirrors upstream `StdRng::next_u64()`.
  // May straddle a ChaCha20 block boundary.
  std::uint64_t NextU64();

 private:
  // Reads `n` bytes from the keystream into `out`, refilling the
  // block buffer as needed. `n` MUST be <= 64 (used internally
  // only for n in {4, 8}).
  void ReadBytes(std::uint8_t* out, std::size_t n);

  // Encrypts 64 zero bytes through ChaCha20 into block_; resets
  // block_pos_ to 0. Called whenever ReadBytes finds the buffer
  // empty or partially consumed.
  void RefillBlock();

  evp_cipher_ctx_st* ctx_ = nullptr;
  std::array<std::uint8_t, 64> block_;
  std::size_t block_pos_ = 64;  // 64 = empty (forces RefillBlock)
};

}  // namespace primihub::pir::frodo

#endif  // SRC_PRIMIHUB_KERNEL_PIR_OPERATOR_FRODO_PIR_FRODO_PRNG_H_
