version: '3'
services:
  mysql:
    image: $MYSQL_IMAGE
    container_name: mysql
    restart: always
    env_file:
      - ./data/env/mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: $REDIS_IMAGE
    container_name: redis
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    # ports:
    #   - "6379:6379"

  rabbitmq:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq
    restart: always
  
  nacos:
    image: $NACOS_IMAGE
    container_name: nacos-server
    restart: always
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
    ports:
      - "8848:8848"
      # - "9848:9848"
      # - "9555:9555"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8848/nacos"]
      interval: 10s
      timeout: 10s
      retries: 3

  meta:
    image: $PRIMIHUB_META
    container_name: meta
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/meta.jar \
        --server.port=8080 \
        --grpc.server.port=9099 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=node \
        --spring.cloud.nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.config.namespace=node"
    ports:
      - "9099:9099"
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8080/fusion/healthConnection"]
      interval: 15s
      timeout: 3s
      retries: 3
  
  application:
    image: $PRIMIHUB_PLATFORM
    container_name: application
    restart: always
    volumes:
      - "./data:/data"
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar \
        --spring.rabbitmq.host=rabbitmq \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=node \
        --nacos.config.namespace=node"
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8090/healthConnection"]
      interval: 10s
      timeout: 10s
      retries: 3

  gateway:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar \
        --server.port=8080 \
        --spring.cloud.nacos.discovery.server-addr=nacos:8848 \
        --nacos.config.server-addr=nacos:8848 \
        --spring.cloud.nacos.discovery.namespace=node \
        --nacos.config.namespace=node"
    depends_on:
      - application

  nginx:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: manage-web
    restart: always
    volumes:
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30080:80"
    depends_on:
      - gateway

  node:
    shm_size: '6gb'
    # network_mode: "host"
    image: $PRIMIHUB_NODE
    container_name: node
    restart: "always"
    # enable TEE
    # devices:
    #   - /dev/sgx/enclave
    #   - /dev/sgx/provision
    ports:
      - "50050:50050"
    volumes:
      - ./config/node0.yaml:/app/config/node0.yaml
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --config=/app/config/node0.yaml"
    depends_on:
      meta:
        condition: service_healthy

  loki:
    image: $LOKI_IMAGE
    container_name: loki
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    volumes:
      - ./data:/data
    ports:
      - 3100:3100

networks:
  primihub_net: