package(default_visibility = ["//visibility:public"])

cc_test(
    name = "task_config_parser_test",
    size = "small",
    srcs = ["task_config_parser_test.cc"],
    deps = [
        "//src/primihub/cli:run_task_lib",
        "@com_google_googletest//:gtest_main",
        "@nlohmann_json",
    ],
)
